assignment/mirafatechnology/mirafa/appblog/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^book_list/$', views.BookList.as_view(), name="book_list"),
    url(r'^add_book/$', views.AddBook.as_view(), name="add_book"),
    url(r'^(?P<pk>\d+)/detail/$', views.BookDetailView.as_view(),
        name='detail'),
    url(r'^(?P<pk>\d+)/comment/$', views.BookCommentView.as_view(),
        name='comment'),
    url(r'^(?P<pk>\d+)/update/$', views.BookupdateStatusView.as_view(),
        name='update'),
    url(r'^(?P<pk>\d+)/rating/$', views.BookUpdateRatingView.as_view(),
        name='rating'),
    url(r'^(?P<pk>\d+)/like/$', views.BookLikeView.as_view(),
        name='like'),
    

    
]

assignment/mirafatechnology/mirafa/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.user_login),
    url(r'register/$', views.register),
    url(r'^about/$',views.AboutView.as_view()),
]

assignment/mirafatechnology/mirafa/mirafa/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^appblog/', include('appblog.urls', namespace="appblog")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
]

assignment/mirafatechnology/mirafa/appblog/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone


CHOICE = (
    ('OUTOFSTOCK', 'OUTOFSTOCK'),
    ('INSTOCK', 'INSTOCK')
)
CATEGORY = (
    ('Science fiction','Science fiction'),
    ('Drama','Drama'),
    ('Romance','Romance'),
    ('Horror','Horror')
)


class Book(models.Model):
    title = models.CharField(max_length=50)
    created_at = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User)
    author = models.CharField(max_length=50)
    publisher = models.CharField(max_length=60)
    description = models.TextField()
    price = models.IntegerField()
    category_books = models.CharField(
        max_length=40,
        choices=CATEGORY, default='Drama'
    )
    book_no = models.IntegerField(blank=True)
    status = models.CharField(
        max_length=40,
        choices=CHOICE, default='INSTOCK'
    )
    updated = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        book_no = Book.objects.count()
        if book_no == 0:
            self.book_no = 1
        else:
            self.book_no = book_no + 1
        return super(Book, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title

# Cooment for each book
class BookComment(models.Model):

    book_comment = models.ForeignKey(Book, null=True, blank=True)
    user = models.ForeignKey(User, blank=True, null=True)
    person_name = models.CharField(max_length=50)
    date = models.DateTimeField(default=timezone.now)
    email = models.EmailField()
    body = models.TextField()
    rating = models.IntegerField(default=0)
    like = models.IntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(default=timezone.now)

    class Meta:
        def __str__(self):
            return self.name

assignment/mirafatechnology/mirafa/appblog/forms.py
from django import forms
from .models import BookComment, Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'publisher','description','price','category_books','status')


class BookCommentForm(forms.ModelForm):
    class Meta:
        model = BookComment
        fields = ('person_name', 'email', 'body')


class BookUpdateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['status', ]


class RatingUpdateForm(forms.ModelForm):
    class Meta:
        model = BookComment
        fields = ['rating', ]

assignment/mirafatechnology/mirafa/appblog/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic import ListView, View, DetailView
from .models import Book, BookComment
from .forms import BookForm, BookCommentForm, BookUpdateForm, RatingUpdateForm
from django.shortcuts import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

# To display all book information
from django.db.models import Count
class BookList(ListView):
    template_name = 'book_list.html'
    model = Book

    def get_context_data(self, **kwargs):
        context = super(BookList, self).get_context_data(**kwargs)
        context['form'] = BookForm()
        context['book_count'] = Book.objects.count()
        context['books'] = Book.objects.all().order_by('-created_at')
        return context

# To  add books, make sure only authenticated person can add the books.

class AddBook(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            form = BookForm(request.POST)
            if form.is_valid():
                instance = form.instance
                instance.save()
                form.save()
                messages.success(
                    request, 'Well done!Your book is Addded Succesfully.')
            else:
                print form.errors
            return HttpResponseRedirect('/appblog/book_list/')
        except Exception as e:
            print e

# Display the detail page of the each book

class BookDetailView(DetailView):
    template_name = 'book_detail.html'
    model = Book

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['form'] = BookCommentForm()
        context['book'] = Book.objects.get(pk=self.kwargs.get('pk'))
        context['form1'] = BookUpdateForm(instance=context['book'])
        context['form2'] = RatingUpdateForm(instance=context['book'])
        return context

# Inside detail of each book, user can put comment on boooks
class BookCommentView(View):

    def post(self, request, *args, **kwargs):
        form = BookCommentForm(request.POST)
        if form.is_valid():
            instance = form.instance
            book = Book.objects.get(pk=self.kwargs.get('pk'))
            instance.book = book
            form.save()
            messages.success(
                request, 'Well done!Your Comment is Added Succesfully.')
        else:
            print form.errors
        return HttpResponseRedirect(
            '/appblog/{0}/detail/'.format(self.kwargs.get('pk')))

# Only authenticated user can change the status of the book,whether book is instock or out of stock
class BookupdateStatusView(LoginRequiredMixin,View):

    def post(self, request, *args, **kwargs):
        book = Book.objects.get(pk=self.kwargs.get('pk'))
        form1 = BookUpdateForm(request.POST, instance=book)
        if form1.is_valid():
            form1.save()
            messages.success(
                request, 'Well done!Your status is updated succesfully.')
        else:
            print form1.errors
        return HttpResponseRedirect(
            '/appblog/{0}/detail/'.format(book.id))


class BookUpdateRatingView(View):
    def post(self, request, *args, **kwargs):
        book = Book.objects.get(pk=self.kwargs.get('pk'))
        form2 = RatingUpdateForm(request.POST,instance=book)
        if form2.is_valid:
            form2.save()
            messages.success(
                request, 'Well done!Your status is updated succesfully.')
        else:
            print form1.errors
        return HttpResponseRedirect(
            '/appblog/{0}/detail/'.format(book.id))


class BookLikeView(View):
    def post(self, request, *args, **kwargs):
        book = Book.objects.get(pk=self.kwargs.get('pk'))
        book.bookcomment_set.filter(like=2)
        book.save()
        messages.success(
            request, 'Well done!Your item is changed Succesfully.')
        return HttpResponseRedirect(
            '/appblog/{0}/detail/'.format(book.id))

assignment/mirafatechnology/mirafa/appblog/templates/book_detail.html
		
		<!-- To add comment on each book in detail page -->
		
		<p> <form action="{% url 'appblog:comment' pk=book.id %}"  method="post">
           	{{form.as_p}}
           	{% csrf_token %}</p>
           	<p><button type="submit" class="btn btn-success">Submit</button></p>
        </form>


        <!-- To display the comment on each book -->
         {% for comment in book.bookcomment_set.all %}
         	<h1 style="font-size:80%;">Name of the User :<strong> {{comment.person_name}}</strong></h1>{{comment.email}}
         	<h2><p><strong><h2 style="font-size:80%;"user comment:</strong> <mark>{{comment.body}}</mark></p></h2><small> {{comment.date}}</small>
         		</hr>
         {% endfor %}

         <!-- To update the status of book  -->
      		<form action="{% url 'appblog:update' pk=book.id %}" method="post">
		        {{form1.as_p}}
		        {% csrf_token %}
		        <p><button type="submit" class="btn btn-success">update</button>
	       </form>

         <!-- To update the rating of book  -->
          <form action="{% url 'appblog:rating' pk=book.id %}" method="post">
            {{form2.as_p}}
            {% csrf_token %}
            <p><button type="submit" class="btn btn-success">update</button>
         </form>



         <div class="row">
      <div class='col-sm-12 col-md-12 col-lg-12' >   
        <form action="{% url 'appblog:like' pk=book.id %}" method='get'>
         {% csrf_token %}
         <button type="submit" class="btn btn-danger"  >like </button>
        </form>
        <br>
      </div>
    </div>

assignment/mirafatechnology/mirafa/appblog/templates/book_list.html
<!-- this will count total number of books available in the store -->
		{{book_count}}



<!-- list or display all book parameters -->
	{% for book in books %}
  		{{book.title}} 
	    {{book.author}}
	    {{book.publisher}}
	    {{book.description}}
	    {{book.status}}
	    {{book.price}}
	    {{book.category_books}}
    	<a href="{% url 'appblog:detail' pk=book.id %}">View Detail</a>
    {% endfor %}


<!-- Add book -->

 	<p> <form  method="post" action="." enctype="multipart/form-data">
      	{{form.as_p}}
       	{% csrf_token %}</p>
       <p><button type="submit" class="btn btn-success">Submit</button></p>
    </form>